baseURL = "https://billiam.github.io/cncjs-pendant-streamdeck/"
languageCode = "en-us"
title = "CNCjs Pendant Stream Deck"
theme = "whisper"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = false
pygmentsUseClasses = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Docs"
    url = "/docs/"
    weight = 2

[params]
  google_analytics_id=""
  homepage_button_link = '/docs'
  homepage_button_text = 'Read The Docs'
  homepage_intro = 'A CNCjs pendant for mobile web and the Elgato Stream Deck'
  homepage_image = '/images/web.gif'

  ## You can enable to add anchor links to header elements
  enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "CNCjs pendant for mobile web and the Elgato Stream Deck"
    meta_og_title = "CNCjs Pendant Stream Deck"
    meta_og_type = "website"
    meta_og_url = "https://billiam.github.io/cncjs-pendant-streamdeck"
    meta_og_image = "https://billiam.github.io/cncjs-pendant-streamdeck/jog.png"
    meta_og_description = "CNCjs pendant for mobile web and the Elgato Stream Deck"
    meta_twitter_card = "summary"
    meta_twitter_site = ""
    meta_twitter_creator = "@billiporter"

  [params.logo]
    mobile = ""
    standard  = ""
